# Generated by Django 3.0.4 on 2020-03-28 06:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCopyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정일시')),
                ('number', models.IntegerField(db_index=True, verbose_name='번호')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='제목')),
                ('artist', models.CharField(db_index=True, max_length=200, verbose_name='음악가')),
                ('stock_income_rate', models.FloatField(db_index=True, verbose_name='최저가 기준 주식 1주당 예상 수익')),
                ('last_12_months_income', models.IntegerField(default=0, verbose_name='지난 12개월 수익')),
                ('stock_lowest_price', models.IntegerField(default=0, verbose_name='주식 최저가')),
                ('stock_sales', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='판매중 주식')),
            ],
            options={
                'verbose_name': '음악 저작권',
                'verbose_name_plural': '음악 저작권',
            },
        ),
    ]
