# Generated by Django 3.0.4 on 2020-03-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccopyright',
            name='stock_income_rate',
            field=models.FloatField(db_index=True, verbose_name='주당 수익률'),
        ),
    ]
